Repository neurobagel/tools, pull requests merged in 2024-05, with the labels that each got.

#6 [ENH] Add JSON formatting matching, annotations-only changes check, tests
  .github/workflows/test.yml
  .pre-commit-config.yaml
  app/api/models.py
  app/api/routers/openneuro.py
  app/api/utility.py
  tests/__init__.py
  tests/conftest.py
  tests/test_data/original/0_indents.json
  tests/test_data/original/0_indents_singleline_nonewline.json
  tests/test_data/original/0_indents_singleline_withnewline.json
  tests/test_data/original/2tab_indents.json
  tests/test_data/original/3_indents.json
  tests/test_data/updated/0_indents.json
  tests/test_data/updated/0_indents_singleline_nonewline.json
  tests/test_data/updated/2tab_indents.json
  tests/test_data/updated/3_indents.json
  tests/test_utility.py
Labels: pr-minor

#8 [ENH] Add path parameter for repo ID and logic when repo/file does not exist
  app/api/dictionary_utils.py
  app/api/routers/openneuro.py
Labels: pr-minor

#10 [CI] Add wf to build `nightly` Docker image
  .github/workflows/build_docker.yml
Labels: skip-release

#13 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/handle_external_pr.yml
Labels: _bot

#17 [CI] Update DockerHub repo name
  .github/workflows/build_docker.yml
Labels: pr-internal

#18 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/pull_request_template.md
  .github/workflows/build_docker_on_release.yml
  .github/workflows/release.yaml
Labels: _bot
