Repository neurobagel/tools, pull requests merged in 2024-09, with the labels that each got.

#26 [ENH] Remove auth and open a PR on data dictionary upload
  .pre-commit-config.yaml
  README.md
  app/api/models.py
  app/api/routers/example_synthetic.json
  app/api/routers/openneuro.py
  app/api/utility.py
  app/main.py
  docker-compose.yml
  pytest.ini
  requirements.txt
  tests/test_auth.py
  tests/test_utility.py
Labels: pr-minor, release

#27 [ENH] Add favicon and welcome message at root endpoint
  app/main.py
Labels: pr-patch, release

#29 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/build_docker_nightly.yml
Labels: _bot
